### ISSUE TITLE
Issue on the buttons on feedback panel

### ISSUE THREAD

**Issue by Bowuigi** [dreamdream2020/scorched-pixel-dungeon#1]
Requirements (필요):
- What happens... (버그 내용)
- When I do something... (상황, 조건)
- My device is... (기종)

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)

Do I have to keep the requirements?
(I am not a native English speaker)

I am on Android 8.1.0 (Motorola G5), latest version as of December 20
The buttons aren't working properly on Spanish (It's only on this screen from what I saw, idk if this happens in other languages)
![Screenshot_20201220-235426](https://user-images.githubusercontent.com/70549864/102734555-e087ad00-431e-11eb-9fef-d6f0ce4bdc60.png)
From lonesome developer to lonesome developer,  the game seems awesome!

**Comment by dreamdream2020** [comment]
Hello there! It's very thankful to your feedback :)
However I'm not good at foreign languages except english (handle only a little bit) and korean (my native language), so unfortunately this issue can't be solved for a while 😂 From lonesome developer to lonesome developer, thanks again to your help and wish to enjoy!
