### ISSUE TITLE
이단자로 물건을 구매할 때 무기에 걸린 저주의 효과가 발생

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#10]
Requirements (필요):
- What happens... (버그 내용) 무기에 걸린 저주가 공격이 아닌 다른 상황에서도 발생
- When I do something... (상황, 조건) 이단자로 플레이 중 무기에는 양극화의 저주가 걸려 있었으며, 이 때 상점에서 물건을 샀을 때 상인과 소환수에게 취약이 걸리는 이펙트가 발생함과 동시에 상인이 사라짐
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![1608802195768_1608802195768_1](https://user-images.githubusercontent.com/76470428/103079250-d31c3c80-4616-11eb-8f21-0161deef4c51.gif)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)화이팅

**Comment by dreamdream2020** [comment]
아 이거 뭔지 알거같은데... 혹시 거울상 같은거 쓰고 있었음?

**Comment by dreamdream2020** [comment]
이것도 해결! https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/8adcaa695cb405976d37c1d6f7eb1d0af90cb8cc
