### ISSUE TITLE
크래쉬

### ISSUE THREAD

**Issue by hellohelloy1** [dreamdream2020/scorched-pixel-dungeon#11]
Requirements (필요):
- What happens... (버그 내용) 크래쉬
- When I do something... (상황, 조건) 연금술사, 하수구에서 어느 순간 크래쉬
- My device is... (기종) 갤럭시 s20

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
- 크래쉬 조건을 모르겟서요 ㅠㅠ  죄송 재밌개하고있슴
  (외로운 1인 개발자를 위한 응원 메세지)

**Comment by hellohelloy1** [comment]
전부 다 파리를 +1총으로 근접거리에서 때릴때였던것같은디 정확하진 않아요

**Comment by hellohelloy1** [comment]
아 총쏠때 크래쉬나네요 방금확인함

**Comment by hellohelloy1** [comment]
아니네요 맨손으로 때혀도 크래쉬네요 암튼 공격할때 튕김

**Comment by hellohelloy1** [comment]
특정 적을 죽일 때 뜨는 것 같네요. 죽일때 튕긴 적은 어떤 방법으로 죽여도 튜ㅣㅇ기는듯

**Comment by dreamdream2020** [comment]
크래쉬 조건을 조금 더 구체적으로 제보해줘요ㅠㅠ 최신 버전으로 업데이트 해둔거 맞죠?!
