### ISSUE TITLE
이단자 저주 숙련 특성의 효과 적용이 안 되는 버그

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#12]
Requirements (필요):
- What happens... (버그 내용) 저주 융합을 한 방어구에 강화의 주문서를 사용했을 때 저주가 사라지면서 강화 수치가 내려가는 것을 확인(+8 -> +9 과정에서 저주가 사라지면서 +8로 유지되는 것을 확인 가능), 이후 저주가 없는 +14 판금 갑옷이 남음
- When I do something... (상황, 조건) +2판금 갑옷에 저주 융합을 한 상태, 저주 숙련을 +2까지 배운 상태에서 판금 갑옷에 강화의 주문서를 12개 사용
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![1608803102444_1608803102444_1](https://user-images.githubusercontent.com/76470428/103080154-99e4cc00-4618-11eb-9350-9ffd0c299db5.gif)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지) 재밌게 하고 있어

**Comment by dreamdream2020** [comment]
아하 머가 문젠지 찾았다 언제나 제보 고마워!

**Comment by dreamdream2020** [comment]
해결했다! https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/8adcaa695cb405976d37c1d6f7eb1d0af90cb8cc

**Comment by Hoto-Mocha** [comment]
최고야
