### ISSUE TITLE
소환수가 보스 방 밖에 나가 있는 것처럼 보이는 버그

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#13]
Requirements (필요):
- What happens... (버그 내용) 소환수가 잠깐 보스 아레나 밖에 나가 있는 것처럼 보임
- When I do something... (상황, 조건) 소환후가 소환되어 있는 상태로 드워프 제왕 보스 아레나 진입
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![1608803626945_1608803626945_1](https://user-images.githubusercontent.com/76470428/103080635-9271f280-4619-11eb-89ce-f9e2773e9541.gif)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지) 최고야

**Comment by dreamdream2020** [comment]
요건 암만 해봐도 재현이 안된다... 이쪽에서 확인되는대로 고쳐볼게 고마워!
