### ISSUE TITLE
이단자 거추장스러운 저주 효과 미발동

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#14]
Requirements (필요):
- What happens... (버그 내용) 이단자의 거추장스러운 갑옷 효과가 발동하지 않음
- When I do something... (상황, 조건) 이단자로 거추장스러운 판금 갑옷 +17을 입고 문을 지나가도 적이 공포에 걸리지 않음(설명에 '공격자에게'라고 적혀 있어서 문을 지나는 도중에 맞아 봐도 공포는 걸리지 않음을 확인)
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![1608805441648_1608805441647_1](https://user-images.githubusercontent.com/76470428/103082643-ea125d00-461d-11eb-87d1-d65299c98abe.gif)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지) 힘내

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/8adcaa695cb405976d37c1d6f7eb1d0af90cb8cc 아마 이러면 될거야... 아마도!

**Comment by Hoto-Mocha** [comment]
버그인 건 맞는거지?
