### ISSUE TITLE
Fatal bug

### ISSUE THREAD

**Issue by giogio27** [dreamdream2020/scorched-pixel-dungeon#15]
Requirements (필요):
- Every 4th floor on new heroes crash the game
Additional (선택):
- Stay safe and strong sir.

**Comment by dreamdream2020** [comment]
Can you tell me when you last updated it?? Thx to report!

**Comment by giogio27** [comment]
It was the latest patch adding the Alchemist hero

**Comment by dreamdream2020** [comment]
Ummm well then try [this](https://github.com/dreamdream2020/scorched-pixel-dungeon/releases/download/0.9.1base/scorched-pixel-dungeon.apk) : Can you start a new game with this version? I think there can be savefile problem created old-version...

**Comment by giogio27** [comment]
Gonna try that. Is that tweaked or original one?
