### ISSUE TITLE
크래쉬 조건

### ISSUE THREAD

**Issue by hellohelloy1** [dreamdream2020/scorched-pixel-dungeon#16]
Requirements (필요):
- What happens... (버그 내용) 크래쉬
- When I do something... (상황, 조건) 연금술사로 적을 죽일 때. 층은 무작위이고, 한번 적을 죽일때 크래쉬가 뜨면 불러오기를 해도 그 층에선 무조건 적을 죽이면 크래쉬가 뜸

- My device is... (기종)

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)

언젠간 연애에 성공할 거에요!

**Comment by hellohelloy1** [comment]
아 최신버전임

**Comment by hellohelloy1** [comment]
![videotogif_2020 12 25_17 19 10](https://user-images.githubusercontent.com/76554932/103127500-69af3300-46d5-11eb-9848-bf4609e7ac05.gif)

이런식으로 튕겨서 뭐가 문제인지 우리로서는 잘 모르겠ㅇ.ㅁ

**Comment by dreamdream2020** [comment]
혹시 4번째 슬롯에 유물이나 반지 끼고있던거 없음???

**Comment by hellohelloy1** [comment]
방금 다시 해봤는데, 4번째 슬롯에 유물 장착후 튕긴 층에서 4번째 슬롯 비워놓고 플레이- 절반정도 하다 문제없어서 다시 착용- 플레이하다 튕김- 유물 다시 착용하기 직전의 시점으로 로드됨. 슬롯문제일수도 있을듯.
