### ISSUE TITLE
크래시떠서 앱이 꺼짐

### ISSUE THREAD

**Issue by jjp8000** [dreamdream2020/scorched-pixel-dungeon#17]
Requirements (필요):
- What happens... (버그 내용) 연금술사 총으로 적을 쏠때 튕기고 그층 내려왓을때로 돌아옴

- When I do something... (상황, 조건) 정확한조건은 모르겟는데 대도의팔찌가 문제로 보임
 상황은 1층에서 낙하방으로 낙하해서 대도팔찌를 먹고 장착하고 유령퀘를 깨고 적들 쏘고 다니다가 크래시나서 낙하햇을때로 돌아감
 4번정도 크래시떠서 대도팔찌를 안끼고 3층으로와서 낀뒤 또 총쏘고다니니까 또 튕기기 시작
 방금은 돈일부러안먹고 3층돌앗는데 또 튕김
 한번더 돈안먹고햇는데 19발째에 튕김
 또해봣는데 또 19발째임 뭐지
 발수는 중요한게아닌가 이번엔 13발임
 대도팔찌 빼고돌다가 뒤짐 아 ㅋㅋ 튕기진않앗음
일단 의심가는건 대도팔찐데 확신은없다

다음판에서 또튕겻는데 이번엔 복귀시점이 연금술로 총강화한시점이고 팔찌는없고 부적이 있음

- My device is... (기종) 갤럭시 s6엣지

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
힘내요!

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/b2285f9d0860f6ff61293cbdc16f84ae786408b9 해결! 매번 고마워!
