### ISSUE TITLE
연금술사가 적을 죽이면 크래시가 남

### ISSUE THREAD

**Issue by ghost** [dreamdream2020/scorched-pixel-dungeon#18]
Requirements (필요):
- What happens... (버그 내용) 특정 적을 죽일때 크래시
- When I do something... (상황, 조건) 반지칸에 유물 장착했을때 크래시가 터짐. 유물을 낀 상태로 같은 적을 세번 죽여보니 크래시가 계속 터지고 유물을 빼니 정상적으로 진행됨
- My device is... (기종) 갤럭시 A9pro

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)

**Comment by dreamdream2020** [comment]
오케이오케이 이런거 진짜 고맙다ㅜㅠ 원인을 정확하게 짚어줬어 덕분에 삽질할거 1분만에 끝냈다 https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/b2285f9d0860f6ff61293cbdc16f84ae786408b9
