### ISSUE TITLE
이단자 크래쉬 버그

### ISSUE THREAD

**Issue by hellohelloy1** [dreamdream2020/scorched-pixel-dungeon#19]
Requirements (필요):
- What happens... (버그 내용) 튕김
- When I do something... (상황, 조건) 이단자 2단계특 유령타락찍고 타락한 유령이 유령과 교전시 튕기는듯
- My device is... (기종)s20

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)

**Comment by hellohelloy1** [comment]
다시 시험해보니 적 유령이 아군유령 때릴때 튕김

**Comment by hellohelloy1** [comment]
굳이 적 유령이 아니더라도, 아군 유령과 적이 교전할때 튕기는 것 같네요..

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/95edd3937b217dadff86f0ba414b429765103f87 여기서 이미 해결된 버그니까 최신 설치파일로 다시 받아서 다시 설치해봐요!
