### ISSUE TITLE
연금술사 비밀 연금술 방 크래시 발생 관련

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#2]
Requirements (필요):
- What happens... (버그 내용) 크래시가 발생하는 것을 확인(3번 크래시 발생/3번의 시도)
- When I do something... (상황, 조건) 연금술사로 비밀방에 있는 연금술 솥과 상호작용하면
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![Screenshot_20201222-170049](https://user-images.githubusercontent.com/76470428/102864328-4b4bfc00-4477-11eb-8437-65aa873cc857.jpg)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)  최고야

**Comment by dreamdream2020** [comment]
오케이 확인함 고마워!

**Comment by dreamdream2020** [comment]
요것도 해결함! https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/8989192d7d771747d220b6a3ec851afaacd6421e
