### ISSUE TITLE
련금술 물약상자 크래시 버그?

### ISSUE THREAD

**Issue by NounKim** [dreamdream2020/scorched-pixel-dungeon#20]
Requirements (필요): 연금술사로 이전에 사망한 상태
- What happens... 연금술사 시작 후 무덤파기로 저주받은 연금술 물약상자를 먹은 후 몬스터를 죽이면 계속 크래시가 일어남
- When I do something... (상황, 조건)
- My device is... (기종) v 20

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  재밌게 하고 있습니다 힘내십쇼

**Comment by dreamdream2020** [comment]
요건 https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/b2285f9d0860f6ff61293cbdc16f84ae786408b9 이때 이미 고쳐둔 버그같은데, 한번 최신 설치파일로 다시 받아서 해봐요!
