### ISSUE TITLE
연금술사 장전하는 강화 특성 적용 불가

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#21]
Requirements (필요):
- What happens... (버그 내용) 장전하는 강화 특성 +2를 배운 후 물약이 주입된 권총에 힘의 물약을 주입하여 강화하면 기존에 주입된 물약의 효과가 사라짐. 단순히 텍스트를 잘못 입력했거나 버그거나 둘중 하나인듯
- When I do something... (상황, 조건) 위와 동일
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![1609206360794_1609206360794_1](https://user-images.githubusercontent.com/76470428/103253199-7f697480-49c3-11eb-921e-d0cd7cc9cf97.gif)
![Screenshot_20201229-104749](https://user-images.githubusercontent.com/76470428/103253204-842e2880-49c3-11eb-8ce9-8acd04f5f242.jpg)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지) 재밌게 하고 있어

**Comment by dreamdream2020** [comment]
아앗 요건 텍스트 고치다 만거 맞다! 영문판만 고쳐두고 정작 한국어는 고치다 말았네 제보 고마워!
