### ISSUE TITLE
에테르와 경험치 상호작용 크래시

### ISSUE THREAD

**Issue by asdfj3** [dreamdream2020/scorched-pixel-dungeon#22]
첫 캐를 이단자로 생성한 후, 에테르 노강을 착용한 채 레벨을 올릴 시 튕김
사실 어떤 경우가 문제인진 모르겠으나, 경험치와 에테르와의 상호작용에서 문제가 있는거 같음.
직접 무기로 처치할 경우 크래시나며 이전에 저장된 시점(계단)에서 시작하게 됨
독가스나 낙사로 처치시 크래시 이후, 적을 처치한 시점에서 시작함. 이 경우 경험치는 25/25에 고정되며 이후 적을 처치할경우 반복됨
두 경우 이후 에테르를 벗은후 처치하니 정상적으로 게임이 흘러갔음

**Comment by dreamdream2020** [comment]
양식에 맞춰서 제보해주세요! 해당 버그는 https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/b2285f9d0860f6ff61293cbdc16f84ae786408b9 에서 수정되어 패치되었습니다!
