### ISSUE TITLE
원소술사 버그

### ISSUE THREAD

**Issue by Fruitybite** [dreamdream2020/scorched-pixel-dungeon#23]
Requirements (필요):
- What happens... (버그 내용)
  1. 테스트용으로 추가하신듯한 시작아이템 (강화 주문서, 전직의 서, 신비한 바늘 등)이 그대로 남아있음
  2. 화염, 서리, 번개 원소의 주문 설명 부분에서 피해량이 제대로 표시되지 않고 %1$d-%2$d 형태로 깨져나옴
- When I do something... (상황, 조건)
  새로 업데이트된 설치파일을 설치한 직후 발견
- My device is... (기종)
  블루스택
ㅡ
Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
힘내세요

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/a11347c7a141c1cca69fcf6815f9664c1a5efe14 해결되었습니다. [새로 설치파일을 받으셔서 패치해주세요!](https://github.com/dreamdream2020/scorched-pixel-dungeon/releases/download/0.9.1-0.2/scorched-pixel-dungeon.apk)
