### ISSUE TITLE
원소술사 9층, 12렙

### ISSUE THREAD

**Issue by dhlexpress02030** [dreamdream2020/scorched-pixel-dungeon#24]
Requirements (필요):
레벨12, 9층이고 저장된 게임에 다시 들어가려하면 크래시, 그외 조건은 모르겠음
특성은 
직감1 집중수련2 원소방패2
수력사2 얼음갑옷2 들불2 찍었음
기종은 노트9
생각나는 특징을 써보자면 지깎노한테서 잉걸불 퀘스트, 2강 마탄 받은걸 팔았고 상점에서 부식막대를 사서 쓰고있었음

그대가 로갤의 보배인데스 힘내십쇼

**Comment by dreamdream2020** [comment]
음 이건 세이브파일 깨진거 말고는 달리 생각나는게 없구먼ㅠㅠ 아마 업데이트랑 버그 잡는 패치 연달아 하는 사이에 뭐가 꼬인거같은데, 지금 준 단서만으로는 다른 방법 찾기도 요원하니... 세이브 삭제 및 최신 버전으로 패치 후 뉴-게임 스타트를 처방합니다 흑흑

**Comment by dreamdream2020** [comment]
딴 버그들까지 한꺼번에 잡아와서 방금 막 최신 버전으로 쪄왔으니 부디 즐겜! https://github.com/dreamdream2020/scorched-pixel-dungeon/releases/tag/0.9.1-0.2
