### ISSUE TITLE
수력사 특성 밀치기

### ISSUE THREAD

**Issue by Enjuxx** [dreamdream2020/scorched-pixel-dungeon#25]
Requirements (필요):
- What happens... (버그 내용)
- 수력사 특성 2레벨 밀치기 효과 없음
- 
- When I do something... (상황, 조건)
- 수력사 특성 2레벨, 적이 근접한 상황에서 화염+서리 또는 서리+화염으로 시전하면 (이때 시전 지정이 안 나옴)물폭탄 이펙트는 정상적으로 나오지만 밀쳐지는 효과가 적용되지 않음
- 
- My device is... (기종)
- Galaxy S7

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
힘내

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/a11347c7a141c1cca69fcf6815f9664c1a5efe14 이미 해결된 버그입니닷!
