### ISSUE TITLE
3원소 설명 텍스트 누락

### ISSUE THREAD

**Issue by Enjuxx** [dreamdream2020/scorched-pixel-dungeon#26]
Requirements (필요):
- What happens... (버그 내용)
- 3원소 설명에 피해량 텍스트 누락
- 
- When I do something... (상황, 조건)
- 화염, 서리, 번개 원소 설명에서 데미지가 %1$d-%2$d로 되어있음
- 
- My device is... (기종)
Galaxy S7

Additional (선택):
- Screenshots! (스크린샷!)
- 
![Screenshot_20210103-060437](https://user-images.githubusercontent.com/76897163/103473670-7969fe00-4dde-11eb-97b0-81ed40f0f2fc.png)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
힘내

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/bdef2c9d29a350586db2d2f787f997f3f7880f71 방금 막 때려잡은 버그들 중 하나이니 [최신 버전으로 패치 받아서 설치하고](https://github.com/dreamdream2020/scorched-pixel-dungeon/releases/tag/0.9.1-0.2) 다시 실행하면 될 것!
