### ISSUE TITLE
이단자 2티어 악령기만자 도트 덜 찍힘

### ISSUE THREAD

**Issue by Enjuxx** [dreamdream2020/scorched-pixel-dungeon#27]
Requirements (필요):
- What happens... (버그 내용)
- 악령 기만자 특성 빨간 느낌표 도트 덜 찍힘
- 
- When I do something... (상황, 조건)
- 밑 사진 참고
- 
- My device is... (기종)
Galaxy S7

Additional (선택):
- Screenshots! (스크린샷!)
- 
![spd-20210103-161506-001](https://user-images.githubusercontent.com/76897163/103473718-0745e900-4ddf-11eb-9fa6-0e68e6ada31b.jpg)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
힘내

**Comment by dreamdream2020** [comment]
으잉 요건 원래 저런거 맞아유 ㅇㅇ 디테일한 구석까지 케어해주는 당신께 감사..!
