### ISSUE TITLE
연금술사의 권총에 달달한 치유 영약을 주입하면

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#3]
Requirements (필요):
- What happens... (버그 내용) 연금술사의 권총의 텍스트에 문제가 있음
- When I do something... (상황, 조건) 연금술사의 권총에 달달한 치유 영약을 주입하면 텍스트는 나오지만 효과는 없음을 확인
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![Screenshot_20201223-000928](https://user-images.githubusercontent.com/76470428/102903244-66d4f800-44b3-11eb-8734-3bb882b6590a.jpg)
![Screenshot_20201223-000918](https://user-images.githubusercontent.com/76470428/102903258-69cfe880-44b3-11eb-8d4e-7f0d4d10f492.jpg)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
힘내

**Comment by Hoto-Mocha** [comment]
'재장전하기 전까지, 달달한 치유 영약이 주입된 탄환으로' 가 문제의 문장임. 다른 물약과 달리 권총에서 빛이 나지도 않고, 영약에 따른 효과가 적혀 있지도 않음

**Comment by dreamdream2020** [comment]
해결 완료! https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/3b0772b5a82329051832dd1deb357cbc6e5a00ad
