### ISSUE TITLE
서리 관련 버그

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#30]
Requirements (필요):
- What happens... (버그 내용) 솔직히 어떻게 표현해야 할지 잘 모르겠음. 게가 내 앞으로 다가와서 물 장판 위에서 서리 원소 마법을 맞고 죽은 뒤 조금 있다가 쨍그랑 하면서 사라지고, 나중에 갑자기 죽은 자리에서 한기 디버프가 생김. 사진을 보면 이해가 쉬울지도...
- When I do something... (상황, 조건) 위와 동일
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![1609683970833_1609683970833_1](https://user-images.githubusercontent.com/76470428/103481066-b4d6ed80-4e1b-11eb-804a-1525a4a61130.gif)
![1609684000529_1609684000529_1](https://user-images.githubusercontent.com/76470428/103481084-c8825400-4e1b-11eb-8e77-e87dc3436853.gif)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지) 재밌엉

**Comment by dreamdream2020** [comment]
어...음....이건 녹픽 쪽에서 생기는 버그 같은데, 당장은 해결할 방법이나 정확한 원인은 모르겠다... 혀튼 제보 고마워!
