### ISSUE TITLE
Commentary on Heretic's tier 2 talents.

### ISSUE THREAD

**Issue by Omicronrg9** [dreamdream2020/scorched-pixel-dungeon#31]
Note: The Heretic is a high-difficulty class, so playing him makes you feel harder then original SPD
(참고: 이단자는 높은 난이도의 영웅으로 만들어졌으며, 때문에 원본 녹픽던보다 더 어렵게 느껴질 수 있음)

Hi, playing an heretic round right now. Is it intended that since a certain point in the game we can cycle between curses whenever we want as "Curse Mastery" guarantees?

The game has been really satisfying up to now, thank you and keep the good work.

One last question. I cannot find the recipe or method to get the emberblood, sorry if it was obvious.

Kind regards.

**Comment by dreamdream2020** [comment]
Yes it is **highly** intended!

+and for the clue of 'emberblood'... just remember its name is the only clue. Where you can find the potion which contains the word _'blood' on its name?_
