### ISSUE TITLE
Game crashed on item reforging.

### ISSUE THREAD

**Issue by Omicronrg9** [dreamdream2020/scorched-pixel-dungeon#32]
Reached Troll Blacksmith in floor 14th, tried to reforge two plate mails (one of them cursed but not unequippable) and game crashed when pressed "reforge". I can't take any screenshot as every time I try to access the run the game crashes again.

I am playing on an Android 4.4 emulator, the only one that my PC supports.

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/releases/tag/0.9.1-0.2.1 Fixed! Thanks to report :D
