### ISSUE TITLE
0.2.1버전 버그

### ISSUE THREAD

**Issue by Fruitybite** [dreamdream2020/scorched-pixel-dungeon#33]
1. 세이브파일 증발
한 일 : 0.2 버전에서 트롤 대장장이로 갑옷 합치려다가 벽돌이 된 이단자 세이브를 로드하였음.
일어난 일 : 세이브가 로드되어 대장장이 앞에 있는 화면이 보였으나 즉시 튕긴 후 세이브파일째로 삭제됨.
추정 : 이전 버전 세이브라 호환이 안된듯.

2. 원소술사 플레이중 지속적인 튕김 현상
한 일 : 원소술사(폭풍술사) 플레이.
일어난 일 : 11층 부근부터 전투 도중에 가끔씩 튕기기 시작. 특히 번개 원소로 적을 한번에 여럿 처치했을 때 자주 튕겼고, 반대로 적이 나를 때렸을 때 튕긴 경우는 단 한번 있었음. 일반 층에서 튕겼을 경우에는 시작시점으로 돌아가지만, 보스 층에서 튕기면 전투 상황이 그대로 저장되었음.
추정 : 주로 드워프 구울 여러 개체를 번개 원소로 처치했을때 발생했으니 그쪽과 관련이 있을 것 같음.

3. 요그제바 전투 중 세이브 파일 손상
한 일 : 2번과 동일한 세이브파일로 계속 진행.
일어난 일 : 요그제바 전투 도중 튕겼으나, 2번과는 달리 세이브파일이 손상되어 읽을 수 없다는 오류 메시지가 뜨고 진행이 불가능해짐.
추정 : 모르겠음.

![Screenshot_20210106-034226](https://user-images.githubusercontent.com/67253801/103687449-9fa4bf00-4fd3-11eb-8950-37fd693bfdb6.png)

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/f50325248f69b375e10a8ebd1aed0d6dbd70df8b 고쳐뒀으니까 [새로 설치파일 받아서 적용해주세요!](https://github.com/dreamdream2020/scorched-pixel-dungeon/releases/download/0.9.1-0.2.1/scorched-pixel-dungeon.apk) 안타깝지만 이전 세이브는 묻어두는걸로...
