### ISSUE TITLE
Emberblood buff might be always giving +1 Strength point.

### ISSUE THREAD

**Issue by Omicronrg9** [dreamdream2020/scorched-pixel-dungeon#34]
– **What happens:** I currently have 16 strength but I just obtained the 15 str badge. I have drunk emberblood though I'm not burning. Might it be something related to that? I also have drunk two elixirs of might but that shouldn't be a source of miscalculation. I don't have a ring of might either.
– **My device is:** SmartGaGa emulator, Android 4.4
– **Screenshots:** 
![imagen](https://user-images.githubusercontent.com/13071402/103724317-4db06900-4fd4-11eb-81e2-9430ce97531f.png)

– **Cheer-Up message for lonesome developer:** Keep up with the good work ^^! This mod has a lot of _potential. 

Kind regards.

**Comment by dreamdream2020** [comment]
Always thankful, now this bug is also fixed :D
