### ISSUE TITLE
Game is not reading elemental focus buffs descriptions properly.

### ISSUE THREAD

**Issue by Omicronrg9** [dreamdream2020/scorched-pixel-dungeon#35]
– **What happens:** Just a small typo somewhere that makes the game reading the damage interval wrongly in elemental focus buffs descriptions.
– **My device is:** The same as in the last report, SmartGaGa emulator, Android 4.4
– **Screenshots:**
![imagen](https://user-images.githubusercontent.com/13071402/103763173-c4bc2080-5019-11eb-95a2-53e407e835bd.png)
![imagen](https://user-images.githubusercontent.com/13071402/103763238-d7cef080-5019-11eb-8adc-41777715cfee.png)
![imagen](https://user-images.githubusercontent.com/13071402/103763325-f208ce80-5019-11eb-8a1e-215473177060.png)

– **Cheer-Up message for lonesome developer:** Hope you have a really nice day :)

**Comment by Omicronrg9** [comment]
Apart from that, in order to not overflow the repository with issues, I'm going to post another similar error that the user Alkali Man found, as I also stumbled upon it.

The typical !!!NO TEXT FOUND!!! message appears when identifying an item as an elementarist. My guess is that It might have to do with the double identification talent "Phytoness' intuition".

Here is the screenshot, hope it helps to clarify.
![imagen](https://user-images.githubusercontent.com/13071402/103764040-0bf6e100-501b-11eb-91df-fb96594ca574.png)

Again, have nice day!

**Comment by dreamdream2020** [comment]
Always- Thanks to report :) Guess the second one is clearly caused by pytoness' intuition, however I have no idea why the first one(focus buff typo things) is occured 🤔 Because I can't reproduced it in the Korean version(As you know I'm korean and that means I'm really not good at english 😂) So It will take more time to fix, unlike other bugs. Anyway, thanks to report again!

**Comment by dreamdream2020** [comment]
....HOWEVER I found what's the problem and fix it 😎🔥 https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/e16a474821f34cd94f44a31d4048ffe12cd8fe76 https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/6051ccafaeb86e534d69ca02af1f786dd8669ccd
