### ISSUE TITLE
이단자 텐구닌자 관련 버그

### ISSUE THREAD

**Issue by dhlexpress02030** [dreamdream2020/scorched-pixel-dungeon#38]
텐구닌자 1패턴에서 2강 타락막대로 마비를 건 상태로 텐구닌자가 순간이동(다음패턴으로 넘어가는거 아님)하면 게임이 멈추고 왼쪽위에 턴 바퀴만 계속 돌아감
중독된 상태였음
게임 나갔다 들어가니까 버그 풀림
장비는 노저주 0강 원방, 유령한테받은 2강 사슬갑(변위), 0강 분노반, 3강 장미, 2강 연금 있었고, 장미 소환은 안했고 특성은 2테크 특성중 2개를 안찍은 상태였음

![Screenshot_20210116-103706](https://user-images.githubusercontent.com/73631944/104793942-0d2cc880-57e8-11eb-8972-5e83006f4b4b.jpg)
![Screenshot_20210116-103707](https://user-images.githubusercontent.com/73631944/104793944-128a1300-57e8-11eb-85fe-5490df610621.jpg)

퀵슬롯 추가점..

**Comment by dreamdream2020** [comment]
이건 녹픽던 쪽 버근데 아마 0.9.3 넘어오면서 해결된걸로 알아유
