### ISSUE TITLE
연금술사로 1층 계단을 올라가면 크래시 발생

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#4]
Requirements (필요):
- What happens... (버그 내용) 크래시 발생
- When I do somthing... (상황, 조건) 옌더의 아뮬렛을 들고 1층에 있는 올라가는 계단을 올라 탈출 시 크래시 발생, 재실행 시 랭킹에는 올라가 있음
이후 1층에 새롭게 플레이 중인 연금술사가 추가됨
게임 버전 : 0.9.•base 버전(업데이트 이전에 확인된 이슈임)
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
최고야

**Comment by dreamdream2020** [comment]
![Screenshot_20201224-110315](https://user-images.githubusercontent.com/75399715/103050480-c2000b00-45d7-11eb-9e34-afef3382fd5b.jpg)
크으 드디어 해결했다... 이것도 곧 패치될거임 고마워!

**Comment by Hoto-Mocha** [comment]
능력자 최고야
