### ISSUE TITLE
혈기사 관련 버그

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#40]
Requirements (필요):
- What happens... (버그 내용) 혈기사가 뼈 칼날로 망령을 타락시키면 체력이 가득 차는 버그
- When I do something... (상황, 조건) 관련이 있는지는 모르겠으나 갑옷에 신진대사, 뼈 칼날에 희생의 저주가 붙어 있음
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)![1618369301158_1618369301158_2.gif](https://user-images.githubusercontent.com/76470428/114648595-16abcb00-9d1a-11eb-8062-3e1941bfcc58.gif)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
화이팅

**Comment by dreamdream2020** [comment]
요것도 한꺼번에 해결!
