### ISSUE TITLE
News and Plan: Merge features from 0.9.3

### ISSUE THREAD

**Issue by dreamdream2020** [dreamdream2020/scorched-pixel-dungeon#42]
Long time no see, dungeneers!

I haven't been able to afford to work on this project, due to financial and health problems. It's a personal condition, intractable. (Thank God it has nothing to do with Covid-19, so don't worry! :) I hope all of you are healthy)

I have spent my time fighting illness, recuperating, and trying to solve financial problems- college tuition. I learn really valuable things there, but there are too many jobs that have collapsed by this pandemic. The financial problems of every colleges are so serious, so they abolish academic sholarship😢 (These're common case with everyone my age- becoming a very political issue in Korea)

ANYWAY... In the end, things haven't improved that much so far, but now I can find some time to re-start this project, if not as much as I used to last versons. First goal is importing 0.9.3!

**Comment by alphapsu** [comment]
일단 컴백 축하
0.9.3 적용이면 신직업들의 4티어 특성까지 들어가나요?

**Comment by dreamdream2020** [comment]
> 일단 컴백 축하
> 0.9.3 적용이면 신직업들의 4티어 특성까지 들어가나요?

물론입죠!
