### ISSUE TITLE
트롤배지 텍스트 미발견

### ISSUE THREAD

**Issue by asdfj3** [dreamdream2020/scorched-pixel-dungeon#44]
![Screenshot_20210628-215237](https://user-images.githubusercontent.com/76832273/123640549-3c963580-d85c-11eb-926f-8fdc53e26e21.png)

트롤 해금배지 미발견

새로 설치한 환경인데, 이거랑 무관한거 같음
android 11

**Comment by asdfj3** [comment]
![Screenshot_20210628-220133](https://user-images.githubusercontent.com/76832273/123640772-76ffd280-d85c-11eb-83b9-c555252f6493.png)
![Screenshot_20210628-220127](https://user-images.githubusercontent.com/76832273/123640785-7b2bf000-d85c-11eb-9680-0179a09e3de2.png)


배지 해금시와 해금 후에도 텍스트 미발견

**Comment by dreamdream2020** [comment]
해결! 다시 받아주시면 됩니다아ㅏ
