### ISSUE TITLE
수정 제보

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#45]
Requirements (필요):
- What happens... (버그 내용)
- When I do something... (상황, 조건)
- My device is... (기종)

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)

![Screenshot_20210628-225730.jpg](https://user-images.githubusercontent.com/76470428/123649078-73704980-d864-11eb-842e-1f88d7bec4fb.jpg)
텍스트 안 뜸

![Screenshot_20210628-225745.jpg](https://user-images.githubusercontent.com/76470428/123649119-7c611b00-d864-11eb-884a-6b8e5e457e22.jpg)
꿈결초 -> 꿈풀

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210628-230314.jpg](https://user-images.githubusercontent.com/76470428/123649909-16c15e80-d865-11eb-9637-b8de44d15098.jpg)
+1에
3 동안 -> 3턴 동안

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210628-230723.jpg](https://user-images.githubusercontent.com/76470428/123650510-9cdda500-d865-11eb-8d7b-718dd8680024.jpg)
가로 화면에서 원소술사의 설명창이 잘림

**Comment by dreamdream2020** [comment]
어흑 가로화면에서 잘리는건 제 실력 밖의 문제구먼유... 나머지는 해결했으니 다시 받아주셔유!
