### ISSUE TITLE
이단자로 기습 공격이 안 됨

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#46]
Requirements (필요):
- What happens... 이단자로 기습 공격이 불가
- When I do something... 1층 뱀에게 문 기습을 하려는데 기습이 되지 않음. 어떠한 반지도 끼지 않았으며, 힘이 부족한 것도 아님.
- My device is... 갤럭시 S9+

Additional (선택):
- Screenshots! (스크린샷!)![1624889490316_1624889490316_2.gif](https://user-images.githubusercontent.com/76470428/123651154-3442f800-d866-11eb-94a4-105c2e0dc601.gif)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지) 힘내

**Comment by Hoto-Mocha** [comment]
이제 보니까 기습이 안 되는 게 아니라 문이 안 닫히는 거였네
![1624889654439_1624889654439_2.gif](https://user-images.githubusercontent.com/76470428/123651640-9dc30680-d866-11eb-9ee6-99ac33d90af5.gif)

**Comment by dreamdream2020** [comment]
해결! 다시 받아주심 됩니닷
