### ISSUE TITLE
세이브 파일 실행이 되지않음

### ISSUE THREAD

**Issue by Anzucon** [dreamdream2020/scorched-pixel-dungeon#49]
- 새벽에 하다 자고 이어서 하려니 계속해서 튕김
- 기종은 갤럭시 s10

![Screenshot_20210629-075956](https://user-images.githubusercontent.com/86633405/123713732-04204700-d8b0-11eb-9895-f22f5ea79de4.jpg)
여기서  계속을 누르면 튕긴다는 소리
혹시나 해서 하는 소리긴한데 자기전에 문 버그 수정됐다고 해서 업데이트했는데 그거때문일까요

**Comment by dreamdream2020** [comment]
최신 파일로 다시 설치해보세유!
