### ISSUE TITLE
저주 융합을 한 마법 막대 충전량 버그

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#5]
Requirements (필요):
- What happens... (버그 내용) 저주 융합을 해서 +2로 만든 재성장의 마법 막대 최대 충전량이 3으로 내려감
- When I do something... (상황, 조건) 재성장의 마법 막대에 저주 융합을 해서 총 +2를 만들어 충전량 4를 만들어 사용하고 있었으나 악마의 전당 계층에서 무한로딩 발생(이단자 전설 갑옷 능력이 해제되었을 때 발생) 후 나갔다 등어오니 마법 막대의 충전량이 3까지로 줄어있는 것을 확인
- My device is... (기종) Galaxy S9+

Additional (선택):
- Screenshots! (스크린샷!)
![Screenshot_20201223-111832](https://user-images.githubusercontent.com/76470428/102951885-3b80f600-4511-11eb-928f-6ead807193b4.jpg)

- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)화이팅

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/a7d59669433ecc885cf1192a813fbea4ccb30b3d 얼추 해결하긴 했는데... 이게 어쩌다 생긴건지 모르겠음. 완드 차지수 쪽은 건드린적이 없는데 녹픽쪽 버그인가? 기반 되는 코드를 건드려서 수정한거라 쪼매 불안정할 수 있으니까 딴 버그 없던거 나오면 제보해줘
