### ISSUE TITLE
수정, 버그 제보

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#50]
![Screenshot_20210629-104111_Video Player.jpg](https://user-images.githubusercontent.com/76470428/123724161-cf6bba00-d8c6-11eb-9ce9-7957bbc3282c.jpg)
해악 전이 재사용 대기시간 텍스트가 없음

![Screenshot_20210629-104130_Video Player.jpg](https://user-images.githubusercontent.com/76470428/123724178-d85c8b80-d8c6-11eb-9a7c-71aaf103ac88.jpg)
서리 정령에게서 한기가 걸림과 동시에 침식의 저주 효과가 발동하면 주변에 검은색이 아닌 하늘색 파티클이 나옴. 녹픽던에서도 생기는 버그인지는 모르겠음

기종 갤럭시 S9+

**Comment by Hoto-Mocha** [comment]
추가로, 룬석으로 저주를 걸 때 취소하면 튕기는 버그가 있음

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210629-113736_Video Player.jpg](https://user-images.githubusercontent.com/76470428/123728753-c979d700-d8ce-11eb-91c5-ae50e1c1065b.jpg)
트롤 대장장이 쪽지 주는 텍스트가 안 뜸

![1624934462520_1624934462520_2.gif](https://user-images.githubusercontent.com/76470428/123728855-fa5a0c00-d8ce-11eb-9343-eed902f1efba.gif)
저주 숙련 효과로 강화된 갑옷을 전설 갑옷으로 만들 경우 강화가 추가로 됨. 아무래도 원본 갑옷의 강화수치(저주받은 채라 임시로 강화되어 있음)를 가진 전설 갑옷을 만들고 그게 저주받아 있으니 2강을 추가하는 식으로 되어서 벌어진 일 같음.

**Comment by Hoto-Mocha** [comment]
그리고 어느 순간부터 출혈 폭발로 죽인 적이 혈청 +1 효과를 안 받더라

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210629-124231.jpg](https://user-images.githubusercontent.com/76470428/123734069-9b4cc500-d8d7-11eb-85bb-bdcc3cd0e272.jpg)
제련 -> 재련
제련 : 금속의 원석을 녹여 정제하는 일 - smelt
재련 : 금속이나 목재를 다시 다듬어 연마하는 일 - reforge

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210629-124720.jpg](https://user-images.githubusercontent.com/76470428/123734359-27f78300-d8d8-11eb-917b-44b273a280a4.jpg)
붙태웁니다 -> 불태웁니다
최대치까지 쌓아 공격한 -> 최대치까지 쌓았을 때, 공격해 오는

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210629-124940.jpg](https://user-images.githubusercontent.com/76470428/123734528-7c9afe00-d8d8-11eb-99cc-d10cec2c2338.jpg)
마법막대 -> 마법 막대

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210629-125907.jpg](https://user-images.githubusercontent.com/76470428/123735227-cdf7bd00-d8d9-11eb-9609-6fab1dc8d944.jpg)
자기자신 -> 자기 자신/스스로

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210629-130243.jpg](https://user-images.githubusercontent.com/76470428/123735513-4fe7e600-d8da-11eb-8582-3448e0e85067.jpg)
날라가면 -> 날아가면

**Comment by Hoto-Mocha** [comment]
그리고 이단자로 저주의 룬 사용할 때 장착하지 않은 장비에 사용해도 룬석이 사라짐

**Comment by dreamdream2020** [comment]
> ![Screenshot_20210629-124720.jpg](https://user-images.githubusercontent.com/76470428/123734359-27f78300-d8d8-11eb-917b-44b273a280a4.jpg)
> 붙태웁니다 -> 불태웁니다
> 최대치까지 쌓아 공격한 -> 최대치까지 쌓았을 때, 공격해 오는

그 요건 3단계랑 2단계 효과가 망치/모루로 서로 달라서 그럼 ㅇㅇ

**Comment by dreamdream2020** [comment]
제련은 오리지널 픽던 때부터 Reforge로 쓰던거라 그걸로 고정이고... 나머지 버그들은 전부 고침!
