### ISSUE TITLE
이단자 저주숙련 찍은 후 저주갑옷 벗을 시 튕김

### ISSUE THREAD

**Issue by pwh9882** [dreamdream2020/scorched-pixel-dungeon#51]
Requirements (필요):
- What happens... (버그 내용)
- When I do something... (상황, 조건)
- My device is... (기종)

Additional (선택):
- Screenshots! (스크린샷!)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)

이단자로 특성 저주숙련 3레벨을 찍은 후 저주받은 갑옷을 벗으면 튕김. 

캐릭터 선택창에 갑옷을 벗은 맨몸으로 나오며 다시 접속해도 바로 튕겨서 게임불가.

저주받은 갑옷을 입은 상태에서 다른 갑옷으로 갈아입는것은 가능. (저주받은 갑옷 -> 저주받지 않은 갑옷 은 모르겠음) 

다른 종류(무기나 유물)의 경우는 시도해보지 않아서 모름.

기종: oneplus7t 안드로이드 11

**Comment by dreamdream2020** [comment]
해결됨! 최신 파일로 재설치해서 다시 시도해보셔유 ㅇㅇ!

**Comment by pwh9882** [comment]
FATAL EXCEPTION: SHPD Actor Thread
Process: com.scorchedpixel.scorchedpixeldungeon, PID: 25346
java.lang.NullPointerException: Attempt to read from field 'com.shatteredpixel.shatteredpixeldungeon.items.armor.Armor$Glyph com.shatteredpixel.shatteredpixeldungeon.items.armor.Armor.glyph' on a null object reference
	at com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Hunger.act(Hunger.java:6)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.process(Actor.java:16)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene$2.run(GameScene.java:1)

업데이트 된 버전으로 시도했는데 오류가 났던 세이브 파일은 여전히 튕김. 이 문제도 해결이 가능할까요?

**Comment by dreamdream2020** [comment]
헉 이렇게 로그까지 쫙 따서 가져와주신거 진짜 감사함... 한번 확인해볼게유

**Comment by dreamdream2020** [comment]
혹시 오류났던 세이브에서 갑옷에 신진대사 저주 붙은거 있었나유? 아니면 다른 저주 종류라던가

**Comment by dreamdream2020** [comment]
아마 신진대사 저주 붙은 갑옷에서 문제 생긴거 같아서 그쪽 간단하게 수정해뒀으유 ㅇㅇ! `~\core\src\main\java\com\shatteredpixel\shatteredpixeldungeon\items\armor\curses\Metabolism.java` 에서 살짝 고쳐둔건데 혹시 어케 바꿨나 관심있으면 함 확인해보셔도 좋을듯!
