### ISSUE TITLE
트롤 3-1특성 적용 안됨

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#52]
Requirements (필요):
- What happens... 트롤 대장장이 3-1 특성의 +1과 +2의 효과가 적용이 되지 않음
- When I do something... 스크린샷 참고
- My device is... 갤럭시 S9+

Additional (선택):
- Screenshots! (스크린샷!)
![1624950544499_1624950544499_2.gif](https://user-images.githubusercontent.com/76470428/123753551-f2ad5e00-d8f4-11eb-8b92-0611bce9441b.gif)

![1624950721843_1624950721843_2.gif](https://user-images.githubusercontent.com/76470428/123753560-f5a84e80-d8f4-11eb-8cae-59e9201b9312.gif)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지) 힘내

**Comment by dreamdream2020** [comment]
해결! 매번 감사!
