### ISSUE TITLE
트롤 엔딩씬에서 크래시 발생

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#53]
Requirements (필요):
- What happens... 전쟁장인으로 1층 올라가는 계단을 오를 시 게임이 꺼짐. 랭킹에는 정상진입됨
- When I do something... 위와 동일
- My device is... 갤럭시 S9+

Additional (선택):
- Screenshots! (스크린샷!)![Screenshot_20210629-171419_Video Player.jpg](https://user-images.githubusercontent.com/76470428/123762142-75d2b200-d8fd-11eb-91d8-de0026c0fb61.jpg)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지) 힘내

**Comment by Hoto-Mocha** [comment]
참고로 방금 나온 업데이트 하기 전 버전임

**Comment by dreamdream2020** [comment]
이거 엄청 어이없게 일어나는 버그더라... 겜 끝날때 엔딩씬에 트롤이 쓸 자리가 없어서 생긴거였음
