### ISSUE TITLE
Crash When Got Yendor's orb and Choice 아직 할 일이 남았다

### ISSUE THREAD

**Issue by hyuckkim** [dreamdream2020/scorched-pixel-dungeon#55]
Requirements (필요):
- What happens... (버그 내용) 
Crash
- When I do something... (상황, 조건)
개척자 플레이중 (힘 10 총 10강, 사슬갑옷 10강, 각반 재성장 플레이함) 
옌더의 오브 획득 후 선택지에서 아직 할 일이 남았다 선택
불러오는 중... 장면중 튕김
게임 재실행 후 불러오기 시도시 불러오는 중... 장면중 튕김

- My device is... (기종)
LG v50 ThinkQ
android 10
V500N20z

Additional (선택):
- Screenshots! (스크린샷!)
![Screenshot_20210629-174752](https://user-images.githubusercontent.com/53367179/123768013-e9c38900-d902-11eb-9785-3c6a18914ddc.png)
(에러 메시지 없는 튕김이라서 발견할 수 있는 것이 없었습니다)
 
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
각반 재성장 연금술사 진짜 끝내주게 재밌었어요
파이팅

**Comment by dreamdream2020** [comment]
?? 오브 말고 아뮬렛 말하는거 맞쥬...?

여튼 끝내주게 재밌으셨다니 감사 그리고 감사함 👍

**Comment by dreamdream2020** [comment]
원인 찾았습니닷! 빠르게 패치해서 올라갈테니 곧 최신 파일로 바꿔서 설치하시면 될 것!

**Comment by hyuckkim** [comment]
> ?? 오브 말고 아뮬렛 말하는거 맞쥬...?
> 
> 여튼 끝내주게 재밌으셨다니 감사 그리고 감사함 👍 

아 아뮬렛이 생각이 안났네요😅
