### ISSUE TITLE
이유모를 버그

### ISSUE THREAD

**Issue by asdfj3** [dreamdream2020/scorched-pixel-dungeon#56]
-게임 실행 즉시 캐릭 생성 후 종료하지 않은 상태에서 지우고 다른 캐릭 생성시 튕김.
튕겼다 다시 들어오면 멀쩡히 실행됨. 중간에 종료후 다시 들어와서 삭제시엔 멀쩡함.
- 마지막 릴리즈

스샷 못찍음

**Comment by dreamdream2020** [comment]
이건 정보가 더 필요해유... 생성한 캐릭터/생성한 다른 캐릭터/폰 기종 등등 여러 조건이 겹쳐야 되는거 같은데... 이쪽에선 암만 시도해도 재현이 안 되는 버그입니닷
