### ISSUE TITLE
연금술사 거치식 기관총 탄창 관련

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#58]
![1625020699293_1625020699293_2.gif](https://user-images.githubusercontent.com/76470428/123893726-e5957b00-d997-11eb-8baf-ba3d4840593c.gif)
거치식 기관총 4-1특성으로 탄창을 얻은 후에 움직여도 추가 탄창이 남아 있는데 의도된 거임?
설명에 적힌 대로 '재장전' 할 때만 초기화되는거?

**Comment by dreamdream2020** [comment]
예쓰!
