### ISSUE TITLE
식량 연성 2단계 능력 적용 오류

### ISSUE THREAD

**Issue by Citro3** [dreamdream2020/scorched-pixel-dungeon#6]
Requirements (필요):
- What happens... (식량 연성 2단계 능력 적용 오류)
- When I do something... (설명에는 연금술 에너지 3 감소라고 표기되었지만 실제로는 2만 감소됨)
- My device is... (갤럭시 A 퀀텀)

Additional (선택):
- Screenshots! (스크린샷!)
![Screenshot_20201223-125352](https://user-images.githubusercontent.com/76506513/102957899-fc59a180-451e-11eb-824f-9abaa2c47ab1.jpg)
![Screenshot_20201223-125409](https://user-images.githubusercontent.com/76506513/102957914-054a7300-451f-11eb-9f01-15aca42318a2.jpg)

**Comment by dreamdream2020** [comment]
해결 완료! https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/f9d1a03f630c2abbf8a2334d4253892255e26eeb
