### ISSUE TITLE
세이브 로딩 중 크래시 발생

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#60]
Requirements (필요):
- What happens... 세이브 로딩 중에 게임이 꺼짐
- When I do something... 개척자 21층, 거치식 기관총 4-1특성으로 정탄수가 최대치 이상으로 늘어나 있음
- My device is... 갤럭시 S9+

Additional (선택):
- Screenshots! (스크린샷!)
![Screenshot_20210630-114213.jpg](https://user-images.githubusercontent.com/76470428/123897625-b0d8f200-d99e-11eb-9cdb-205e3e056e70.jpg)
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)

**Comment by Hoto-Mocha** [comment]
![Screenshot_20210630-154756.jpg](https://user-images.githubusercontent.com/76470428/123916419-97df3980-d9bc-11eb-83ad-99d05053741d.jpg)
벌써 2명째 갇혀 있음...

2번째는
![Screenshot_20210630-160557_Video Player.jpg](https://user-images.githubusercontent.com/76470428/123916864-150aae80-d9bd-11eb-990a-cf9f2dd13837.jpg)
여기에서 권총만 추가로 강화해 둔 상태였음. 장탄수는 9/9

**Comment by Hoto-Mocha** [comment]
개척자로 옌더의 부적을 얻고 아직 할 일이 남았다를 누르면 게임이 꺼지고 세이브 로드가 불가능한 것도 확인했음

**Comment by dreamdream2020** [comment]
이제 최신 버전으로 재설치하시면 저게... 돌아올지는 사실 모르겠는데, 적어도 새로 시작한 세이브에선 이런 일이 (적어도 같은 원인으로는) 안 일어날거예유
