### ISSUE TITLE
버그 제보

### ISSUE THREAD

**Issue by Hoto-Mocha** [dreamdream2020/scorched-pixel-dungeon#61]
![Screenshot_20210630-122652.jpg](https://user-images.githubusercontent.com/76470428/123897667-be8e7780-d99e-11eb-9688-4a3e99a707f0.jpg)
이식의 마법 막대로 매혹하고 공격했었는데 단 한번도 마비에 걸린 걸 본 적이 없음(완전 최신 버전은 아님)

![Screenshot_20210630-122709.jpg](https://user-images.githubusercontent.com/76470428/123897670-c0583b00-d99e-11eb-8de6-9621b4f1954a.jpg)
대응력을 지닌 채로 처음 적을 맞추면 대응력이 즉시 사라짐(혹시 원래는 대응력이 탄환을 빗맞췄을 때도 사라지는거임?), 대응력을 소모해도 맞은 적이 1턴간 마비에 걸리지 않음

**Comment by Hoto-Mocha** [comment]
확인 결과 개척자에서 3-3특 하나만 찍고 빈 곳에 총알을 발사해도 대응력이 사라지지 않았음. 적을 맞춰서 데미지를 주면 사라지고.

즉 3-5특 +1이랑 +3 효과 발동이 아예 안 됨

**Comment by Hoto-Mocha** [comment]
3-5특의 +2를 찍기 전과 찍은 이후의 데미지를 비교해 봤는데 크게 달라진 것이 없음을 확인, 3-5특 전체가 아예 적용이 안 됨

**Comment by dreamdream2020** [comment]
해결했으요!
