### ISSUE TITLE
The game crashes if I want to get past level 2

### ISSUE THREAD

**Issue by Bowuigi** [dreamdream2020/scorched-pixel-dungeon#8]
Requirements (필요):
- What happens... (버그 내용)
The game crashes when I try to descend past the second level with alchemist
- When I do something... (상황, 조건)
Any way of getting past the level 2 (falling, going through stairs, etc.) crashes the game
Also when I fall the game crashes, I load the save and take damage (and get the debuffs) without going to the next level
- My device is... (기종)
Motorola G5
Android 8.1.0
Additional (선택):
- Screenshots! (스크린샷!)
![Screenshot_20201223-114008.png](https://user-images.githubusercontent.com/70549864/103008660-3cffed80-4514-11eb-9d20-258dc683ee17.png)
Me about to go down
![Screenshot_20201223-114014.png](https://user-images.githubusercontent.com/70549864/103008697-4db06380-4514-11eb-9427-903c87dd93c0.png)
The game crashing (translation: Scorched Pixel Dungeon keeps failing
x Exit app
- Cheer-Up message for lonesome developer
  (외로운 1인 개발자를 위한 응원 메세지)
From lonesome developer to lonesome developer, the alchemist class is my favorite lol

**Comment by Bowuigi** [comment]
Wait forgot to put the title lol
Edit: the title exists now

**Comment by Bowuigi** [comment]
The bug only happens with the alchemist class, I tried it recently with most class

**Comment by dreamdream2020** [comment]
I think this bug was fixed at https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/8989192d7d771747d220b6a3ec851afaacd6421e ! Can you re-install apk and try again? Always, Thanks a lot 😄

**Comment by Bowuigi** [comment]
It works again!
