### ISSUE TITLE
완드 최대 충전량이 0이 됨

### ISSUE THREAD

**Issue by alphapsu** [dreamdream2020/scorched-pixel-dungeon#9]
Requirements (필요):
- What happens... (제목 그대로) 
- When I do something... (연금술사 플레이 도중 업데이트를 하자마자 모든 완드의 최대 충전량이 0이 됨)
- My device is... (기종)

Additional (선택):
- Screenshots! (
![Screenshot_20201224-151321](https://user-images.githubusercontent.com/76548598/103065708-993d3d00-45fa-11eb-8e7c-a1036a18ca3e.jpg)
)
- Cheer-Up message for lonesome developer
  (재밌게 하고 있습니다)

**Comment by dreamdream2020** [comment]
새로 만든 캐릭터도 그런가요? https://github.com/dreamdream2020/scorched-pixel-dungeon/issues/5 여기서 나타난 버그 잡느라 완드 관련된 코드를 심하게 건드렸는데 그거때매 세이브파일 손상된걸수도 있어요. 세이브 손상된건 안타깝지만 구제할 방법이 없고... 강줌 하나 바르거나 저주융합 쓰거나 하면 돌아올수도 있는데, 오히려 더 손상될수도 있으니까 딴 캐릭으로 시작하심이 좋을듯...

**Comment by alphapsu** [comment]
![Screenshot_20201224-160655](https://user-images.githubusercontent.com/76548598/103069145-14eeb800-4602-11eb-9cfc-1f7c8df0a077.jpg)
완드 관련 버그 추가:마법사 선택해서 게임 들어왔다 나갔다하면 최대 충전량이 늘어남 최대 10까지

**Comment by dreamdream2020** [comment]
https://github.com/dreamdream2020/scorched-pixel-dungeon/commit/8adcaa695cb405976d37c1d6f7eb1d0af90cb8cc 해결!
